package pwr.tin.tip.sw.pd.cu.ti.jms.themes;

public class Themes {

	public final static String esbIn = "<algorithm><sessionId>1</sessionId><algorithmId>1</algorithmId><algorithmEndpoint>eai:TestAlgorithm1</algorithmEndpoint><sourceFilePath>//path/to/file/withName</sourceFilePath><resultFilePath>//path/to/file/withName</resultFilePath></algorithm>";
	public final static String esbOutProcessed = "<algorithm><sessionId>1</sessionId><algorithmId>1</algorithmId><status>PROCESSED</status><startDate>2010-09-20 12:23:45</startDate><endDate>2010-09-20 12:23:46</endDate><time>1234</time></algorithm>";
	public final static String esbOutWithWorning = "<algorithm><sessionId>1</sessionId><algorithmId>1</algorithmId><status>WARNING</status><warningDesc>Komunikat opisuj¹cy zdarzenie</warningDesc><startDate>2010-09-20 12:23:45</startDate><endDate>2010-09-20 12:23:46</endDate><time>1234</time></algorithm>";
	public final static String esbOutWithErrors = "<algorithm><sessionId>1</sessionId><algorithmId>1</algorithmId><status>ERROR</status><errorDesc>Komunikat opisuj¹cy zdarzenie</errorDesc><startDate>2010-09-20 12:23:45</startDate><endDate>2010-09-20 12:23:46</endDate><time>1234</time></algorithm>";
	public final static String fiveBloksParallel = "<message><messageId>1</messageId><scenerio><scenerioId>1</scenerioId><scenerioName>Przyk³ad_2</scenerioName><scenerioDescription>Przy³ad scenariusza z przypadkiem zrównoleglenia zadañ.</scenerioDescription><start><next>1</next></start><components><algorithm><algorithmId>1</algorithmId><algorithmName>Pierwszy Algorytm</algorithmName><algorithmEndpoint>eai:TestAlgorithm1</algorithmEndpoint><next>2</next></algorithm><algorithm><algorithmId>2</algorithmId><algorithmName>Drugi Algorytm</algorithmName><algorithmEndpoint>eai:TestAlgorithm2</algorithmEndpoint><next>3</next><next>4</next><prev>1</prev></algorithm><algorithm><algorithmId>3</algorithmId><algorithmName>Trzeci Algorytm</algorithmName><algorithmEndpoint>eai:TestAlgorithm3</algorithmEndpoint><next>5</next><prev>2</prev></algorithm><algorithm><algorithmId>4</algorithmId><algorithmName>Czwarty Algorytm</algorithmName><algorithmEndpoint>eai:TestAlgorithm4</algorithmEndpoint><next>5</next><prev>2</prev></algorithm><algorithm><algorithmId>5</algorithmId><algorithmName>Piaty Algorytm</algorithmName><algorithmEndpoint>eai:TestAlgorithm5</algorithmEndpoint><prev>3</prev><prev>4</prev></algorithm></components><end><prev>5</prev></end></scenerio></message>";
}
